import type { Concursante, Catch, EspeciePez } from './types';

export const mockConcursantes: Concursante[] = [
  {
    id: 1,
    numero_equipo: 101,
    club: 'Club de Pesca y Deportes Náuticos "Monday"',
    distancia: 0,
    pais: 'Paraguay',
    nombre_embarcacion: 'El Tiburón',
    matricula: 'PY-TIB-123',
    telefono: '+595981123456',
    timonero: { nombre: 'Juan Pérez', edad: 45, sexo: 'Masculino', categoria: 'Adultos (Masculino)' },
    acompanante1: { nombre: 'Ana García', edad: 38, sexo: 'Femenino', categoria: 'Damas' },
    acompanante2: { nombre: 'Pedro Pérez', edad: 15, sexo: 'Masculino', categoria: 'Juvenil' },
    totalPoints: 0,
  },
  {
    id: 2,
    numero_equipo: 102,
    club: 'Club de Pesca de Encarnación',
    distancia: 300,
    pais: 'Paraguay',
    nombre_embarcacion: 'La Sirena',
    matricula: 'PY-SIR-456',
    telefono: '+595971789012',
    timonero: { nombre: 'Carlos Sánchez', edad: 66, sexo: 'Masculino', categoria: 'Máster' },
    acompanante1: { nombre: 'Laura Martinez', edad: 58, sexo: 'Femenino', categoria: 'Senior' },
    totalPoints: 0,
  },
];


export const mockCatches: Catch[] = [];

export const mockEspecies: EspeciePez[] = [
    { id: 1, nombre: "SURUBI 50 CM.", puntuacionPieza1: 75, puntuacionPieza2: 75, puntuacionPieza3: 150, medidaCmPieza1: 50, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 2, nombre: "PIRA PARA 50 CM.", puntuacionPieza1: 75, puntuacionPieza2: 75, puntuacionPieza3: 150, medidaCmPieza1: 50, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 3, nombre: "MANGURUYU 50 CM.", puntuacionPieza1: 75, puntuacionPieza2: 75, puntuacionPieza3: 150, medidaCmPieza1: 50, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 4, nombre: "SALMON 40 CM.", puntuacionPieza1: 75, puntuacionPieza2: 75, puntuacionPieza3: 150, medidaCmPieza1: 40, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 5, nombre: "PACU 40 CM.", puntuacionPieza1: 75, puntuacionPieza2: 75, puntuacionPieza3: 150, medidaCmPieza1: 40, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 6, nombre: "DORADO 40 CM.", puntuacionPieza1: 75, puntuacionPieza2: 75, puntuacionPieza3: 150, medidaCmPieza1: 40, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 7, nombre: "ARMADO APRETADOR", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 8, nombre: "ARMADO COMUN", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 9, nombre: "ARMADO COCHI", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 10, nombre: "APRETADOR RAYADO (GUARANI)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 11, nombre: "APRETADOR TORITO (TA YOPY)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 12, nombre: "BOGA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 30, medidaCmPieza2: 32, medidaCmPieza3: 35, medidaObligatoriaPieza1: true, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 13, nombre: "BAGRE AMARILLO Y/O BLANCO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 14, nombre: "BAGRE CHALECO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 15, nombre: "BAGRE COVÍ", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 16, nombre: "BAGRE MARINERITO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 17, nombre: "BAGRE MONCHOLO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 18, nombre: "BAGRE PORTEÑO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 19, nombre: "BAGRE YURUPITO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 25, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: true, medidaObligatoriaPieza3: false },
    { id: 20, nombre: "CORVINA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 21, nombre: "DIENTUDO COLA ROJA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 22, nombre: "DIENTUDO BLANCO O PIOJOSO/ SAN PEDRO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 23, nombre: "MANGURUYU ABÁ", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 24, nombre: "MORENA COMUN (BLANCA O ALBINA)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 25, nombre: "MORENA TROMPUDA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 26, nombre: "MORENA NEGRA (REDONDA O REY)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 27, nombre: "PAPATERRA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 28, nombre: "PATY JHOVY (CANAL)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 29, nombre: "PIRAÑA COMÚN / SYBA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 30, nombre: "PIRÁ GUYRÁ O MACHETE", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 31, nombre: "PIRÁ KYGUA (FARELA O ALEMAN)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 32, nombre: "PIRÁ YAGUA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 33, nombre: "PICO DE PATO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 34, nombre: "PLATO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 35, nombre: "RAYA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 36, nombre: "RELOJITO ROJO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 37, nombre: "RELOJITO BLANCO", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 38, nombre: "RUBITA (VIREINA)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 39, nombre: "SARDINA O SARDINETA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 40, nombre: "SOLALINDE", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 41, nombre: "TIBURONCITO O GOMOSO AZUL", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 42, nombre: "TARE-Y (TARAIRA)", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 43, nombre: "TRES PUNTOS", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false },
    { id: 44, nombre: "MBOCAYA / TILAPIA", puntuacionPieza1: 50, puntuacionPieza2: 50, puntuacionPieza3: 100, medidaCmPieza1: 0, medidaCmPieza2: 0, medidaCmPieza3: 0, medidaObligatoriaPieza1: false, medidaObligatoriaPieza2: false, medidaObligatoriaPieza3: false }
];